version: '3.8'

services:
  massflix-local:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: massflix-local
    restart: unless-stopped
    ports:
      - "3001:3001"  # Application Node.js + React
    volumes:
      # Base de données locale persistante
      - massflix_data:/data
      
      # Montage des datasets TrueNAS Scale
      # ⚠️ ADAPTEZ CES CHEMINS selon votre configuration TrueNAS
      - ${TRUENAS_MOVIES_PATH:-./demo-data/movies}:/media/movies:ro
      - ${TRUENAS_SERIES_PATH:-./demo-data/series}:/media/series:ro
      - ${TRUENAS_POSTERS_PATH:-./demo-data/posters}:/media/posters:ro
      - ${TRUENAS_BANNERS_PATH:-./demo-data/banners}:/media/banners:ro
    environment:
      - NODE_ENV=production
      - JWT_SECRET=${JWT_SECRET:-massflix-secret-key-change-this}
      - MEDIA_PATH=/media
      - DB_PATH=/data/massflix.db
      - PORT=3001
    networks:
      - massflix-local-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/api/content"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # Scanner de médias local
  media-scanner-local:
    build:
      context: .
      dockerfile: Dockerfile.scanner-local
    container_name: massflix-scanner-local
    restart: unless-stopped
    volumes:
      # Mêmes volumes que l'application principale
      - ${TRUENAS_MOVIES_PATH:-./demo-data/movies}:/media/movies:ro
      - ${TRUENAS_SERIES_PATH:-./demo-data/series}:/media/series:ro
      - ${TRUENAS_POSTERS_PATH:-./demo-data/posters}:/media/posters:ro
      - ${TRUENAS_BANNERS_PATH:-./demo-data/banners}:/media/banners:ro
    environment:
      - MASSFLIX_API_URL=http://massflix-local:3001/api
      - MEDIA_PATH=/media
      - SCAN_INTERVAL=${SCAN_INTERVAL:-3600}
    depends_on:
      massflix-local:
        condition: service_healthy
    networks:
      - massflix-local-network

networks:
  massflix-local-network:
    driver: bridge

volumes:
  massflix_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/data