apiVersion: v1
kind: Service
metadata:
  name: {{ include "massflix.fullname" . }}-service
  labels:
    {{- include "massflix.labels" . | nindent 4 }}
    component: app
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      {{- if and (eq .Values.service.type "NodePort") .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
  selector:
    {{- include "massflix.selectorLabels" . | nindent 4 }}
    component: app