// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './database.types';

const SUPABASE_URL = "https://hoowaqdxwvcfwwvanixo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhvb3dhcWR4d3ZjZnd3dmFuaXhvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgxODQ0OTEsImV4cCI6MjA3Mzc2MDQ5MX0.SiUTQJ7-jL7TvIey10JwIKL5bPIYpRKo8l3B5nQpWtc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});